#include "images.h"

const ext_img_desc_t images[25] = {
    { "back", &img_back },
    { "brightness", &img_brightness },
    { "chevron_down", &img_chevron_down },
    { "close", &img_close },
    { "film", &img_film },
    { "fwd10", &img_fwd10 },
    { "lock", &img_lock },
    { "lock_big", &img_lock_big },
    { "next", &img_next },
    { "pause", &img_pause },
    { "play", &img_play },
    { "prev", &img_prev },
    { "queue", &img_queue },
    { "repeat", &img_repeat },
    { "repeat_one", &img_repeat_one },
    { "rescan", &img_rescan },
    { "rew10", &img_rew10 },
    { "sdcard", &img_sdcard },
    { "sdcard_big", &img_sdcard_big },
    { "sdcard_error_big", &img_sdcard_error_big },
    { "seek_back", &img_seek_back },
    { "seek_fwd", &img_seek_fwd },
    { "settings", &img_settings },
    { "shuffle", &img_shuffle },
    { "warning", &img_warning },
};